-- Fix metadata column types
ALTER TABLE `$PREFIX_PLOTGROUPS` MODIFY COLUMN metadata MEDIUMTEXT;
ALTER TABLE `$PREFIX_DISTRICTS` MODIFY COLUMN metadata MEDIUMTEXT;
ALTER TABLE `$PREFIX_RESIDENTS` MODIFY COLUMN metadata MEDIUMTEXT;
ALTER TABLE `$PREFIX_TOWNS` MODIFY COLUMN metadata MEDIUMTEXT;
ALTER TABLE `$PREFIX_NATIONS` MODIFY COLUMN metadata MEDIUMTEXT;
ALTER TABLE `$PREFIX_WORLDS` MODIFY COLUMN metadata MEDIUMTEXT;
ALTER TABLE `$PREFIX_TOWNBLOCKS` MODIFY COLUMN metadata MEDIUMTEXT;

-- Allow plot groups to store a UUID here
ALTER TABLE `$PREFIX_PLOTGROUPS` MODIFY COLUMN town VARCHAR(36);
