name: Feature request
description: Suggest an idea for this project
title: 'Suggestion: '
labels: [enhancement]
body:
    - type: textarea
      attributes:
          label: '**Please explain your feature request to the best of your abilities:**'
      validations:
          required: true
