package com.palmergames.bukkit.util;

import org.bukkit.Material;
import org.jetbrains.annotations.Nullable;

public class MaterialUtil {

	@Nullable
	public static Material getItemFromMaterial(Material material) {
		return switch (material) {
		case CARROTS -> Material.CARROT;
		case POTATOES -> Material.POTATO;
		case BEETROOTS -> Material.BEETROOT;
		case SWEET_BERRY_BUSH -> Material.SWEET_BERRIES;
		case PUMPKIN_STEM, ATTACHED_PUMPKIN_STEM -> Material.PUMPKIN;
		case MELON_STEM, ATTACHED_MELON_STEM -> Material.MELON;
		case WALL_TORCH -> Material.TORCH;
		case REDSTONE_WIRE -> Material.REDSTONE;
		case OAK_WALL_SIGN -> Material.OAK_SIGN;
		case SPRUCE_WALL_SIGN -> Material.SPRUCE_SIGN;
		case BIRCH_WALL_SIGN -> Material.BIRCH_SIGN;
		case ACACIA_WALL_SIGN -> Material.ACACIA_SIGN;
		case CHERRY_WALL_SIGN -> Material.CHERRY_SIGN;
		case JUNGLE_WALL_SIGN -> Material.JUNGLE_SIGN;
		case DARK_OAK_WALL_SIGN -> Material.DARK_OAK_SIGN;
		case MANGROVE_WALL_SIGN -> Material.MANGROVE_SIGN;
		case BAMBOO_WALL_SIGN -> Material.BAMBOO_SIGN;
		case OAK_WALL_HANGING_SIGN -> Material.OAK_HANGING_SIGN;
		case SPRUCE_WALL_HANGING_SIGN -> Material.SPRUCE_HANGING_SIGN;
		case BIRCH_WALL_HANGING_SIGN -> Material.BIRCH_HANGING_SIGN;
		case ACACIA_WALL_HANGING_SIGN -> Material.ACACIA_HANGING_SIGN;
		case CHERRY_WALL_HANGING_SIGN -> Material.CHERRY_HANGING_SIGN;
		case JUNGLE_WALL_HANGING_SIGN -> Material.JUNGLE_HANGING_SIGN;
		case DARK_OAK_WALL_HANGING_SIGN -> Material.DARK_OAK_HANGING_SIGN;
		case MANGROVE_WALL_HANGING_SIGN -> Material.MANGROVE_HANGING_SIGN;
		case CRIMSON_WALL_HANGING_SIGN -> Material.CRIMSON_HANGING_SIGN;
		case WARPED_WALL_HANGING_SIGN -> Material.WARPED_HANGING_SIGN;
		case BAMBOO_WALL_HANGING_SIGN -> Material.BAMBOO_HANGING_SIGN;
		case REDSTONE_WALL_TORCH -> Material.REDSTONE_TORCH;
		case SOUL_WALL_TORCH -> Material.SOUL_TORCH;
		case WATER_CAULDRON -> Material.CAULDRON;
		case LAVA_CAULDRON -> Material.CAULDRON;
		case POWDER_SNOW_CAULDRON -> Material.CAULDRON;
		case COCOA -> Material.COCOA_BEANS;
		case TRIPWIRE -> Material.STRING;
		case SKELETON_WALL_SKULL -> Material.SKELETON_SKULL;
		case WITHER_SKELETON_WALL_SKULL -> Material.WITHER_SKELETON_SKULL;
		case ZOMBIE_WALL_HEAD -> Material.ZOMBIE_HEAD;
		case PLAYER_WALL_HEAD -> Material.PLAYER_HEAD;
		case CREEPER_WALL_HEAD -> Material.CREEPER_HEAD;
		case DRAGON_WALL_HEAD -> Material.DRAGON_HEAD;
		case PIGLIN_WALL_HEAD -> Material.PIGLIN_HEAD;
		case WHITE_WALL_BANNER -> Material.WHITE_BANNER;
		case ORANGE_WALL_BANNER -> Material.ORANGE_BANNER;
		case MAGENTA_WALL_BANNER -> Material.MAGENTA_BANNER;
		case LIGHT_BLUE_WALL_BANNER -> Material.LIGHT_BLUE_BANNER;
		case YELLOW_WALL_BANNER -> Material.YELLOW_BANNER;
		case LIME_WALL_BANNER -> Material.LIME_BANNER;
		case PINK_WALL_BANNER -> Material.PINK_BANNER;
		case GRAY_WALL_BANNER -> Material.GRAY_BANNER;
		case LIGHT_GRAY_WALL_BANNER -> Material.LIGHT_GRAY_BANNER;
		case CYAN_WALL_BANNER -> Material.CYAN_BANNER;
		case PURPLE_WALL_BANNER -> Material.PURPLE_BANNER;
		case BLUE_WALL_BANNER -> Material.BLUE_BANNER;
		case BROWN_WALL_BANNER -> Material.BROWN_BANNER;
		case GREEN_WALL_BANNER -> Material.GREEN_BANNER;
		case RED_WALL_BANNER -> Material.RED_BANNER;
		case BLACK_WALL_BANNER -> Material.BLACK_BANNER;
		case TORCHFLOWER_CROP -> Material.TORCHFLOWER_SEEDS;
		case PITCHER_CROP -> Material.PITCHER_POD;
		case DEAD_TUBE_CORAL_WALL_FAN -> Material.DEAD_TUBE_CORAL_FAN;
		case DEAD_BRAIN_CORAL_WALL_FAN -> Material.DEAD_BRAIN_CORAL_FAN;
		case DEAD_BUBBLE_CORAL_WALL_FAN -> Material.DEAD_BUBBLE_CORAL_FAN;
		case DEAD_FIRE_CORAL_WALL_FAN -> Material.DEAD_FIRE_CORAL_FAN;
		case DEAD_HORN_CORAL_WALL_FAN -> Material.DEAD_HORN_CORAL_FAN;
		case TUBE_CORAL_WALL_FAN -> Material.TUBE_CORAL_FAN;
		case BRAIN_CORAL_WALL_FAN -> Material.BRAIN_CORAL_FAN;
		case BUBBLE_CORAL_WALL_FAN -> Material.BUBBLE_CORAL_FAN;
		case FIRE_CORAL_WALL_FAN -> Material.FIRE_CORAL_FAN;
		case HORN_CORAL_WALL_FAN -> Material.HORN_CORAL_FAN;
		case CRIMSON_WALL_SIGN -> Material.CRIMSON_SIGN;
		case WARPED_WALL_SIGN -> Material.WARPED_SIGN;
		case POWDER_SNOW -> Material.POWDER_SNOW_BUCKET;
		case CAVE_VINES -> Material.GLOW_BERRIES;
		case BIG_DRIPLEAF_STEM -> Material.BIG_DRIPLEAF;
		default -> null;
		};
	}
}
