name: Towny
main: com.palmergames.bukkit.towny.Towny
version: 0.81.0.0
author: Shade, Modified by FuzzeWuzze. Forked by ElgarL
website: http://code.google.com/a/eclipselabs.org/p/towny/
description: >
    Resident-Town-Nation heirarchy combined with a grid based
    protection system. Including a war event.

softdepend: [MultiVerse,Multiverse-Core,XcraftGate,My Worlds,Citizens]

############################################################
# +------------------------------------------------------+ #
# |                   Towny commands                     | #
# +------------------------------------------------------+ #
############################################################

commands:
    towny:
        aliases: []
    nation:
        aliases: [n, nat]
    plot:
        aliases: []
    resident:
        aliases: [res, p, player]
    town:
        aliases: [t]
    townyadmin:
        aliases: [ta]
    townyworld:
        aliases: [tw]

############################################################
# +------------------------------------------------------+ #
# |                     Permissions                      | #
# +------------------------------------------------------+ #
############################################################

permissions:
    towny.admin:
        description: User is able to use /townyadmin, as well as the ability to build/destroy anywhere. User is also able to make towns or nations when set to admin only.
        default: false
        children:
            towny.admin.town: true
            towny.admin.nation: true
            towny.admin.set: true
            towny.admin.reload: true
            towny.admin.reset: true
            towny.admin.toggle: true
            towny.admin.givebonus: true
            towny.admin.backup: true
            towny.admin.newday: true
            towny.admin.purge: true
            towny.admin.unclaim: true
            towny.town.*: true
            towny.nation.*: true
            towny.wild.*: true
            towny.claimed.*: true
            towny.cheat.bypass: true
            towny.top: true
    towny.cheat.bypass:
        description: Disables the anti cheat code for players with this node.
        default: op
    towny.top:
        description: User has access to the "/towny top" commands.
        default: false
    towny.town.*:
        description: User can access all town commands.
        default: false
        children:
            towny.town.new: true
            towny.town.delete: true
            towny.town.rename: true
            towny.town.claim: true
            towny.town.resident: true
            towny.town.plot: true
            towny.town.plottype: true
            towny.town.spawn.*: true
            towny.town.toggle.*: true
    towny.town.spawn.*:
        description: Grants all Spawn travel nodes
        default: false
        children:
            towny.town.spawn.town: true
            towny.town.spawn.nation: true
            towny.town.spawn.ally: true
            towny.town.spawn.public: true
    towny.town.spawn.town:
        description: User is permitted to use /town spawn.
        default: false
        children:
            towny.town.spawn.outpost: true
    towny.town.spawn.nation:
        description: Ability to spawn to other towns within your nation.
        default: false
    towny.town.spawn.ally:
        description: Ability to spawn to towns in nations allied with yours.
        default: false
    towny.town.spawn.public:
        description: Ability to spawn to unaffilated public towns.
        default: false
    towny.town.toggle.*:
        description: User can access all town toggle commands (if a mayor or assistant).
        default: false
        children:
            towny.town.toggle.pvp: true
            towny.town.toggle.public: true
            towny.town.toggle.explosions: true
            towny.town.toggle.fire: true
            towny.town.toggle.mobs: true
    towny.nation.*:
        description: User has access to all nation commands.
        default: false
        children:
            towny.nation.new: true
            towny.nation.delete: true
            towny.nation.rename: true
            towny.nation.grant-titles: true
    towny.town.resident:
        description: User is permitted to join towns.
        default: false
    towny.town.new:
        description: User is able to create a town
        default: false
    towny.town.delete:
        description: User is able to delete their town
        default: false
    towny.town.rename:
        description: User is able to rename their town
        default: false
    towny.town.claim:
        description: User is able to expand with /towny claim
        default: false
        children:
            towny.town.claim.outpost: true
    towny.town.plot:
        description: User is able to purchase and own town plots.
        default: false
        children:
            towny.town.plot.claim: true
            towny.town.plot.unclaim: true
            towny.town.plot.notforsale: true
            towny.town.plot.nfs: true
            towny.town.plot.forsale: true
            towny.town.plot.fs: true
            towny.town.plot.perm: true
            towny.town.plot.toggle: true
            towny.town.plot.set: true
            towny.town.plot.clear: true
    towny.town.plottype:
        description: User is able to alter plot types on plots they own.
        default: false
    towny.town.toggle.pvp:
        description: If a mayor or assistant, the user is able to toggle pvp on/off in their town.
        default: false
    towny.town.toggle.public:
        description: If a mayor or assistant, the user is able to toggle public on/off in their town.
        default: false
    towny.town.toggle.explosions:
        description: If a mayor or assistant, the user is able to toggle explosions on/off in their town.
        default: false
    towny.town.toggle.fire:
        description: If a mayor or assistant, the user is able to toggle fire on/off in their town.
        default: false
    towny.town.toggle.mobs:
        description: If a mayor or assistant, the user is able to toggle mobs on/off in their town.
        default: false
    towny.nation.new:
        description: User is able to create a nation
        default: false
    towny.nation.delete:
        description: User is able to delete their nation
        default: false
    towny.nation.rename:
        description: User is able to rename their nation
        default: false
    towny.nation.grant-titles:
        description: User is able to set titles and surnames for their nation members
        default: false
        
    towny.wild.*:
        description: User can build/destroy/switch/item_use in the wild.
        default: false
        children:
            # You can grant these child nodes and replace the * with a block Id
            # to directly set or negate specific block permissions
            towny.wild.build.*: true
            towny.wild.switch.*: true
            towny.wild.destroy.*: true
            towny.wild.item_use.*: true

    towny.claimed.*:
        description: User can build/destroy/switch/item_use in all towns.
        default: false
        children:
            # You can grant these child nodes and replace the * with a block Id
            # to directly set or negate specific block permissions
            towny.claimed.owntown.build.*: true
            towny.claimed.alltown.build.*: true
            towny.claimed.owntown.item_use.*: true
            towny.claimed.alltown.item_use.*: true
            towny.claimed.owntown.destroy.*: true
            towny.claimed.alltown.destroy.*: true
            towny.claimed.owntown.switch.*: true
            towny.claimed.alltown.switch.*: true
            