name: Compile & Test
on:
    push:
        branches-ignore: [l10n_master]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7
            - name: Set up Java
              uses: actions/setup-java@v6
              with:
                  distribution: 'temurin'
                  java-version: '25'
                  java-package: jdk
                  cache: 'maven'
            - name: Compile with Maven
              run: mvn package -P test
            - name: Upload Artifact
              uses: actions/upload-artifact@v7
              with:
                  archive: false
                  path: |
                    Towny/target/towny-*.jar
                    !Towny/target/towny-*-*.jar
