name: Deploy Pre-release
on:
  workflow_dispatch:
env:
  CURR_VER: 0.0.0.0
  SUPPORTED: " for MC 1.16.* & 1.17.* & 1.18.* & 1.19.*"
jobs:
  deploy_prerelease:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['17']
    name: Deploying Towny Prerelease
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
      - name: Set up Eclipse Temurin
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          java-package: jdk
          cache: 'maven'
      - name: Compile Towny with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B clean package -P no-apidoc
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Get sponsors.txt using PHP
        run: php ./.github/workflows/prerelease/get_sponsors.php
      - name: create staging dir
        run: mkdir staging && cp sponsors.txt staging
      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8 #install the python needed
      - name: execute sponsortable.py
        run: python ./.github/workflows/prerelease/sponsortable.pyw
      - name: execute preRelease.py
        id: prerelease_py
        run: python ./.github/workflows/prerelease/preRelease.py
      - name: create pre-release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ./staging/prerelease.txt
          draft: true
          prerelease: true
          token: ${{ github.token }}
          tag_name: ${{ env.CURR_VER }}
          name: ${{ env.CURR_VER }}${{ env.SUPPORTED }}
          files: |
            ./target/towny-${{ env.CURR_VER }}.jar
        env:
          GITHUB_REPOSITORY: my_gh_org/my_gh_repo
