name: Publish Javadoc on Full Release

on:
  workflow_dispatch:
  release:
    types: [released]
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy JavaDoc 🚀
        uses: MathieuSoysal/Javadoc-publisher.yml@v2.5.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          javadoc-branch: javadoc
          java-version: 21
          target-folder: javadoc/release
          javadoc-source-folder: target/reports/apidocs
          project: maven
